MovieCharacter= "Leonardo DiCaprio in Inception"
print(MovieCharacter.capitalize())
print(MovieCharacter.find("Inception"))
print(MovieCharacter.index("I"))
print(MovieCharacter.isalpha())
print(MovieCharacter.isalnum())
print(MovieCharacter.isdigit())
print(MovieCharacter.islower())
print(MovieCharacter.isupper())
print(MovieCharacter.isspace())
print(MovieCharacter.startswith("Leonardo"))