list_one = ["go", "for", "it"]
print("Before", list_one)
list_one.append("bro")
print("After", list_one)
list_two = list_one.copy()
print("Old List", list_one)
print("New List", list_two)
print(list_one.count("go"))
print(list_one.index("for"))
print(list_one.index("bro"))
list_one.insert(0, "just")
print(list_one)
list_one.remove("just")
print(list_one)
list_one.reverse()
print(list_one)
list_one.sort(key=str.lower, reverse=False) # This sorts the list in alphabetical order
print(list_one)
list_one.pop(0)
print(list_one)
list_one.clear()
print(list_one)